// <auto-generated />
namespace M17E_TrabalhoModelo_2021_22.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class useratualizado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useratualizado));
        
        string IMigrationMetadata.Id
        {
            get { return "202203040945277_user atualizado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
